### ISSUE TITLE
No default country for field in form widget

### ISSUE THREAD

**Issue by ItangSanjana** [backdrop-contrib/addressfield#14]
Addressfield v1.x-1.2.2

Steps to replicate:
1. Install Addressfield module.
2. Add an Addressfield field to a content type.
3. Set Default country `- Site default -`.
4. Create a node and check the address fieldset, default country remain empty.

**Comment by jenlampton** [comment]
Ah, this is because backdrop does not have a default country. Let's simply remove that option.

**Comment by ItangSanjana** [comment]
I am very very sorry for the late response. Actually this issue was fixed by pull request referenced above. IMHO

**Comment by argiepiano** [comment]
I'm revisiting this issue. Actually, Backdrop (1.24.0) does have a default country, which is set at `admin/config/regional/settings`.  Perhaps it was added after this issue was closed.

I believe it would be beneficial to add the option "Site default" to the field settings, and to add the functionality to add pre-select the site default country if no default country was selected in the field settings.  This would mirror D7's current Address Field functionality.

I will submit a new PR, as the PR originally submitted here is very old and the code has changed.

**Comment by argiepiano** [comment]
PR #41 ready for review.
